apiVersion: v1
kind: Service
metadata:
  name: kanban-app
  namespace: kanban
spec:
  selector:
    app: kanban-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
