apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: kanban
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:4.7.6-standalone
          ports:
            - containerPort: 8080
